zesty-io/accounts-ui

- bin/buildIndex.js
- package-lock.json
- src/shell/views/Signup/Signup.js
Adds event tracking to accounts
> Google tracking

- bin/buildIndex.js
- package-lock.json
- src/shell/views/Signup/Signup.js
added adwords conversion tracking to signup
> Google Adwords Tracking

- bin/buildIndex.js
- src/shell/components/AppHeader/AppHeader.js
- src/shell/views/Login/Login.js
- src/shell/views/Login/Login.less
- src/shell/views/Signup/Signup.js
- src/shell/views/Signup/Signup.less
- src/shell/views/TwoFactor/TwoFactor.js
- src/shell/views/TwoFactor/TwoFactor.less
favicon, app logos, and app icon
> 2019 logo update

- bin/buildIndex.js
- src/apps/account/src/views/Account/Account.js
- src/apps/blueprints/src/views/main/Blueprints.js
- src/apps/dashboard/src/views/main/index.js
- src/apps/properties/src/views/PropertiesList/PropertiesList.js
- src/apps/properties/src/views/PropertyOverview/PropertyOverview.js
- src/apps/properties/src/views/main/Properties.js
- src/apps/support/src/views/main/index.js
- src/apps/teams/src/views/main/index.js
- src/shell/components/AppHeader/AppHeader.js
- src/shell/views/App/App.js
- src/shell/views/Login/Login.js
- src/shell/views/Signup/Signup.js
- src/shell/views/TwoFactor/TwoFactor.js
- src/shell/views/VerifyEmail/VerifyEmail.js
this change is to help the user see where they are by looking at the browser tab
Previously 
Now
> Setup title name for view changes

- bin/buildIndex.js
- src/apps/account/src/views/Account/Account.js
- src/shell/views/App/App.js
- src/shell/views/Signup/Signup.js
- Moved Web Developer question to the user account area
- Removed the Email Verification Blocker
- Added AppCues script and user capture
- Wrapped the app with withLoader Router
> Appcues Install for in-app Guides

- src/apps/properties/src/components/Table/Table.js
- src/apps/properties/src/views/PropertyCreate/PropertyCreate.js
- src/apps/properties/src/views/PropertyOverview/PropertyOverview.js
- src/apps/properties/src/views/PropertyOverview/components/AccessTokens/AccessTokens.js
- src/apps/properties/src/views/PropertyOverview/components/AccessTokens/AccessTokens.less
- src/apps/properties/src/views/PropertyOverview/components/NewAccessToken/NewAccessToken.js
- src/apps/properties/src/views/PropertyOverview/components/NewAccessToken/NewAccessToken.less
- src/apps/teams/src/store/teamInvites.js
- src/apps/teams/src/views/main/index.js
Tackles the points on this issue:
https://github.com/zesty-io/accounts-ui/issues/134
> Access tokens post release

- src/apps/properties/src/views/PropertyOverview/PropertyOverview.js
- src/apps/properties/src/views/PropertyOverview/components/LaunchWizard/LaunchWizard.js
> PropertyOverview: initialize domains, access_tokens with empty array

- src/apps/teams/src/components/TeamsGrid/TeamsGrid.js
> TeamInvite: only show unacceped, undeclined, uncancelled invites

- package.json
- src/apps/properties/src/store/sites.js
- src/apps/properties/src/views/PropertyBlueprint/PropertyBlueprint.js
- src/apps/properties/src/views/PropertyBlueprint/PropertyBlueprint.less
> Properties: Update Blueprint new API endpoint

- src/apps/properties/src/components/WebsiteCard/WebsiteCard.js
- src/apps/properties/src/views/PropertyOverview/PropertyOverview.js
- src/apps/properties/src/views/PropertyOverview/PropertyOverview.less
added: swap manager links to new ui
> Manager General Availability

- src/apps/properties/src/views/PropertyOverview/components/PropertyName/PropertyName.js
- src/apps/properties/src/views/PropertyOverview/components/PropertyName/PropertyName.less
Fixed #156 
Fixed broken font-awesome icon and added spacing to save and cancel button
> fixed broken font awesome icon and add spacing to save button

- src/apps/properties/src/store/sites.js
> Instances: fix alpha sort order

- src/shell/views/Login/Login.js
displaying the correct status code message for to many attempts and if invalid logins
fixes #180
> displaying correct  error message

- src/shell/views/Signup/Signup.js
- src/shell/views/Signup/Signup.less
> added SSO button

- src/apps/properties/src/views/PropertyOverview/PropertyOverview.js
propertyOverview now using `http`
> making property overview live domain http

- bin/buildIndex.js
- src/shell/views/App/App.js
> removing appcues

- src/apps/properties/src/store/sites.js
Refactored name sort 
fixes #149
> refactored sort

- src/apps/teams/src/components/TeamCard/TeamCard.js
Team name & description is now editable 
Fixes #189
> fixed team name update

- src/apps/properties/src/views/PropertyOverview/components/PropertyName/PropertyName.js
White space removal on instance edit naming 
fixes #191
> trimmed white space on instance edit names

- package-lock.json
- src/shell/views/Login/Login.js
fixes #195 
Hiding sign up free
> commenting out sign up free div

- src/shell/store/user.js
- src/shell/views/TwoFactor/TwoFactor.js
fixes #153 
fixes https://github.com/zesty-io/accounts-ui/issues/204
> fix 2fa login missing user object

- src/apps/account/src/views/Account/Account.js
fixes #184 
1) hiding  2FA and password reset if SSO is authenticated.
2) converting to functional component
> hiding password and 2FA cards when SSO is authenticated

- package-lock.json
- src/apps/properties/src/views/PropertiesList/components/GridList/GridList.js
Fixes an invite that is missing if the user has favorited the instance before. 
fixes #173
> fixed pending invites from favorite

- package-lock.json
- src/apps/properties/src/components/Table/Table.js
> fixing console warning of descendant p tag

- src/shell/components/AppHeader/AppHeader.js
> change btn name to Try New Accounts (Beta)
